swagger: "2.0"
info:
  title: Student API
  version: 1.0.0
paths:
  /students:
    post:
      summary: Create a new student
      parameters:
        - in: body
          name: body
          description: The student to create
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              age:
                type: integer
      responses:
        201:
          description: Student created successfully
          schema:
            type: object
            properties:
              message:
                type: string
              student:
                $ref: '#/definitions/Student'
        400:
          description: Email already exists
          schema:
            type: object
            properties:
              error:
                type: string
    get:
      summary: Get all students
      responses:
        200:
          description: A list of students
          schema:
            type: array
            items:
              $ref: '#/definitions/Student'
  /students/{email}:
    get:
      summary: Get a student by email
      parameters:
        - in: path
          name: email
          type: string
          required: true
      responses:
        200:
          description: Student found
          schema:
            $ref: '#/definitions/Student'
        404:
          description: Student not found
          schema:
            type: object
            properties:
              error:
                type: string
  /students/{student_id}:
    put:
      summary: Update a student's information
      parameters:
        - in: path
          name: student_id
          type: integer
          required: true
        - in: body
          name: body
          description: The updated student information
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              age:
                type: integer
      responses:
        200:
          description: Student updated successfully
          schema:
            type: object
            properties:
              message:
                type: string
              student:
                $ref: '#/definitions/Student'
        404:
          description: Student not found
          schema:
            type: object
            properties:
              error:
                type: string
    delete:
      summary: Delete a student by ID
      parameters:
        - in: path
          name: student_id
          type: integer
          required: true
      responses:
        200:
          description: Student deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
        404:
          description: Student not found
          schema:
            type: object
            properties:
              error:
                type: string
definitions:
  Student:
    type: object
    properties:
      student_id:
        type: integer
      name:
        type: string
      email:
        type: string
      age:
        type: integer
